// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6"`
	Nickname string `json:"nickname" validate:"required"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type User struct {
	ID       uint64 `json:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Status   int64  `json:"status"`
}

type CreateOrderRequest struct {
	Symbol string `json:"symbol" validate:"required"`           // 交易对符号，如BTC/USDT
	Type   int64  `json:"type" validate:"required,min=1,max=2"` // 订单类型：1-限价单，2-市价单
	Side   int64  `json:"side" validate:"required,min=1,max=2"` // 交易方向：1-买入，2-卖出
	Amount string `json:"amount" validate:"required"`           // 订单数量（基础币种）
	Price  string `json:"price,omitempty"`                      // 订单价格（限价单必填）
}

type CancelOrderRequest struct {
	OrderID uint64 `json:"order_id" validate:"required"` // 订单ID
}

type QueryOrdersRequest struct {
	Symbol string `json:"symbol,omitempty"` // 交易对符号（可选）
	Status int64  `json:"status,omitempty"` // 订单状态（可选）
	Page   int64  `json:"page,omitempty"`   // 页码，默认1
	Size   int64  `json:"size,omitempty"`   // 每页大小，默认20
}

type Order struct {
	ID           uint64 `json:"id"`            // 订单ID
	UserID       uint64 `json:"user_id"`       // 用户ID
	Symbol       string `json:"symbol"`        // 交易对符号
	Type         int64  `json:"type"`          // 订单类型：1-限价单，2-市价单
	Side         int64  `json:"side"`          // 交易方向：1-买入，2-卖出
	Amount       string `json:"amount"`        // 订单总数量
	Price        string `json:"price"`         // 订单价格
	FilledAmount string `json:"filled_amount"` // 已成交数量
	Status       int64  `json:"status"`        // 订单状态：1-待成交，2-部分成交，3-完全成交，4-已取消
	CreatedAt    string `json:"created_at"`    // 创建时间
	UpdatedAt    string `json:"updated_at"`    // 更新时间
}

type OrderListResponse struct {
	Orders []Order `json:"orders"` // 订单列表
	Total  int64   `json:"total"`  // 总数量
	Page   int64   `json:"page"`   // 当前页码
	Size   int64   `json:"size"`   // 每页大小
}

type TradingPair struct {
	ID            uint64 `json:"id"`             // 交易对ID
	Symbol        string `json:"symbol"`         // 交易对符号
	BaseCurrency  string `json:"base_currency"`  // 基础币种
	QuoteCurrency string `json:"quote_currency"` // 计价币种
	MinAmount     string `json:"min_amount"`     // 最小交易数量
	MaxAmount     string `json:"max_amount"`     // 最大交易数量
	PriceScale    int64  `json:"price_scale"`    // 价格精度
	AmountScale   int64  `json:"amount_scale"`   // 数量精度
	Status        int64  `json:"status"`         // 状态：1-正常，2-禁用
	CreatedAt     string `json:"created_at"`     // 创建时间
}

type TradingPairListResponse struct {
	TradingPairs []TradingPair `json:"trading_pairs"` // 交易对列表
}

type OrderBookRequest struct {
	Symbol string `json:"symbol" validate:"required"` // 交易对符号
	Depth  int64  `json:"depth,omitempty"`            // 深度层数，默认20
}

type PriceLevel struct {
	Price  string `json:"price"`  // 价格
	Amount string `json:"amount"` // 数量
}

type OrderBookResponse struct {
	Symbol string       `json:"symbol"` // 交易对符号
	Bids   []PriceLevel `json:"bids"`   // 买盘深度，价格从高到低
	Asks   []PriceLevel `json:"asks"`   // 卖盘深度，价格从低到高
}

type KlineRequest struct {
	Symbol    string `json:"symbol" validate:"required"`   // 交易对符号
	Interval  string `json:"interval" validate:"required"` // 时间周期：1m,5m,15m,1h,4h,1d
	Limit     int64  `json:"limit,omitempty"`              // 返回数量，默认100，最大1000
	StartTime int64  `json:"start_time,omitempty"`         // 开始时间戳（毫秒）
	EndTime   int64  `json:"end_time,omitempty"`           // 结束时间戳（毫秒）
}

type Kline struct {
	OpenTime  int64  `json:"open_time"`  // 开盘时间戳（毫秒）
	CloseTime int64  `json:"close_time"` // 收盘时间戳（毫秒）
	Open      string `json:"open"`       // 开盘价
	High      string `json:"high"`       // 最高价
	Low       string `json:"low"`        // 最低价
	Close     string `json:"close"`      // 收盘价
	Volume    string `json:"volume"`     // 成交量（基础币种）
}

type KlineResponse struct {
	Symbol string  `json:"symbol"` // 交易对符号
	Klines []Kline `json:"klines"` // K线数据列表
}

type TradeHistoryRequest struct {
	Symbol string `json:"symbol" validate:"required"` // 交易对符号
	Limit  int64  `json:"limit,omitempty"`            // 返回数量，默认50，最大500
}

type Trade struct {
	ID        uint64 `json:"id"`         // 成交记录ID
	Symbol    string `json:"symbol"`     // 交易对符号
	Price     string `json:"price"`      // 成交价格
	Amount    string `json:"amount"`     // 成交数量
	Side      int64  `json:"side"`       // 成交方向：1-买入，2-卖出（以taker方向为准）
	CreatedAt int64  `json:"created_at"` // 成交时间戳（毫秒）
}

type TradeHistoryResponse struct {
	Symbol string  `json:"symbol"` // 交易对符号
	Trades []Trade `json:"trades"` // 成交记录列表
}

type Ticker struct {
	Symbol        string `json:"symbol"`         // 交易对符号
	LastPrice     string `json:"last_price"`     // 最新成交价
	Change24h     string `json:"change_24h"`     // 24小时价格变化
	ChangePercent string `json:"change_percent"` // 24小时涨跌幅百分比
	Volume24h     string `json:"volume_24h"`     // 24小时成交量
	High24h       string `json:"high_24h"`       // 24小时最高价
	Low24h        string `json:"low_24h"`        // 24小时最低价
	UpdatedAt     int64  `json:"updated_at"`     // 更新时间戳（毫秒）
}

type TickerResponse struct {
	Ticker Ticker `json:"ticker"` // 统计数据
}

type AllTickersResponse struct {
	Tickers []Ticker `json:"tickers"` // 所有交易对统计数据
}

type Balance struct {
	Currency  string `json:"currency"`   // 币种代码，如BTC、ETH、USDT
	Available string `json:"available"`  // 可用余额
	Frozen    string `json:"frozen"`     // 冻结余额
	UpdatedAt string `json:"updated_at"` // 最后更新时间
}

type BalanceResponse struct {
	Balances []Balance `json:"balances"` // 用户所有币种余额列表
}

type DepositRequest struct {
	Currency string `json:"currency" validate:"required"` // 币种代码
	Amount   string `json:"amount" validate:"required"`   // 充值金额
}

type DepositResponse struct {
	TransactionID string `json:"transaction_id"` // 充值交易ID
	Currency      string `json:"currency"`       // 币种代码
	Amount        string `json:"amount"`         // 充值金额
	Status        int64  `json:"status"`         // 充值状态：1-处理中，2-成功，3-失败
	CreatedAt     string `json:"created_at"`     // 创建时间
}

type WithdrawRequest struct {
	Currency string `json:"currency" validate:"required"` // 币种代码
	Amount   string `json:"amount" validate:"required"`   // 提现金额
	Address  string `json:"address" validate:"required"`  // 提现地址
}

type WithdrawResponse struct {
	TransactionID string `json:"transaction_id"` // 提现交易ID
	Currency      string `json:"currency"`       // 币种代码
	Amount        string `json:"amount"`         // 提现金额
	Address       string `json:"address"`        // 提现地址
	Fee           string `json:"fee"`            // 提现手续费
	Status        int64  `json:"status"`         // 提现状态：1-待审核，2-处理中，3-成功，4-失败
	CreatedAt     string `json:"created_at"`     // 创建时间
}

type AssetHistoryRequest struct {
	Currency string `json:"currency,omitempty"` // 币种代码（可选）
	Type     int64  `json:"type,omitempty"`     // 记录类型：1-充值，2-提现（可选）
	Page     int64  `json:"page,omitempty"`     // 页码，默认1
	Size     int64  `json:"size,omitempty"`     // 每页大小，默认20
}

type AssetTransaction struct {
	ID            string `json:"id"`             // 交易记录ID
	Currency      string `json:"currency"`       // 币种代码
	Type          int64  `json:"type"`           // 记录类型：1-充值，2-提现
	Amount        string `json:"amount"`         // 交易金额
	Fee           string `json:"fee"`            // 手续费
	Status        int64  `json:"status"`         // 交易状态
	Address       string `json:"address"`        // 地址（提现时有值）
	TransactionID string `json:"transaction_id"` // 区块链交易ID
	CreatedAt     string `json:"created_at"`     // 创建时间
	UpdatedAt     string `json:"updated_at"`     // 更新时间
}

type AssetHistoryResponse struct {
	Transactions []AssetTransaction `json:"transactions"` // 交易记录列表
	Total        int64              `json:"total"`        // 总数量
	Page         int64              `json:"page"`         // 当前页码
	Size         int64              `json:"size"`         // 每页大小
}

type CreateTradingPairRequest struct {
	Symbol        string `json:"symbol" validate:"required"`         // 交易对符号，如BTC/USDT
	BaseCurrency  string `json:"base_currency" validate:"required"`  // 基础币种
	QuoteCurrency string `json:"quote_currency" validate:"required"` // 计价币种
	MinAmount     string `json:"min_amount" validate:"required"`     // 最小交易数量
	MaxAmount     string `json:"max_amount" validate:"required"`     // 最大交易数量
	PriceScale    int64  `json:"price_scale" validate:"required"`    // 价格精度
	AmountScale   int64  `json:"amount_scale" validate:"required"`   // 数量精度
}

type UpdateTradingPairRequest struct {
	MinAmount   string `json:"min_amount,omitempty"`   // 最小交易数量
	MaxAmount   string `json:"max_amount,omitempty"`   // 最大交易数量
	PriceScale  int64  `json:"price_scale,omitempty"`  // 价格精度
	AmountScale int64  `json:"amount_scale,omitempty"` // 数量精度
	Status      int64  `json:"status,omitempty"`       // 状态：1-正常，2-禁用
}

type TradingPairStatsResponse struct {
	TotalPairs               int      `json:"total_pairs"`                // 总交易对数量
	ActivePairs              int      `json:"active_pairs"`               // 活跃交易对数量
	DisabledPairs            int      `json:"disabled_pairs"`             // 禁用交易对数量
	SupportedBaseCurrencies  []string `json:"supported_base_currencies"`  // 支持的基础币种
	SupportedQuoteCurrencies []string `json:"supported_quote_currencies"` // 支持的计价币种
}
