version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: exchange-postgres
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - exchange-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exchange_user -d exchange"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: exchange-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - exchange-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  exchange-network:
    driver: bridge